



one = float(input("what is your grade in your Math class? (0.0 - 4.0): "))


two = float(input("what is your grade in your computer science class? (0.0 - 4.0): "))


three = float(input("what is your grade in your english class? (0.0 - 4.0): "))


four = float(input("what is your grade in your advisory class? (0.0 - 4.0): "))


five = float(input("what is your grade in your drawing class? (0.0 - 4.0): "))


six = float(input("what is your grade in your history class? (0.0 - 4.0): "))


seven = float(input("what is your grade in your bioligy class? (0.0 - 4.0): "))


valid = str(print("your average GPA is", + (one + two + three + four + five + six + seven)/7))

if ((valid) > 4.0 ) = true; 
    print("thats not a valid GPA!")
