
adjective1 = input("give me an adjective: ")

adjective2 = input("give me an adjective: ")

type_of_bird = input("give me a type of bird: ")

room_house = input("give me a room in a house: " )

pass_verb = input("give me a pass tense verb: ")

verb = input("give me a verb: ")

rel_name = input("give me a relatives name: ")

noun1 = input("give me a noun: ")

liquid = input("give me a type of liquid: ")

verb_ing = input("give me a verb ending in ing: ")


# i used deep seek (AI) for the mad lib but i coded it in myself
print("It was a " + adjective1 + ", quiet afternoon in the " + room_house + ".")
print("Suddenly, a " + adjective2 + " " + type_of_bird + " " + pass_verb + " against the window.")
print('I heard ' + rel_name + ' yell, "Quick, go ' + verb + ' the ' + noun1 + '!"')
print("We spent the next hour " + verb_ing + " and cleaning up a puddle of " + liquid + ".")
print("What a " + adjective1 + " day it turned out to be!")
