adjective1 = input("give me an adjective: ")

adjective2=input("give me an adjective: ")

type_of_bird = input("give me a type of bird: ")

room_house = input("give me a room in a house:" )

pass_verb = input("give me a pass tense verb:" )

verb = input("give me a verb: ")

rel_name = input("give me a relatives name:" )

noun1 = input("give me a noun: ")

liquid = input("give me a type of liquid: ")

verb_ing = input("give me a verb ending in ing:" )

